-- 1. 현재 시간을 조회한다.
SELECT SYSDATE 
  FROM DUAL -- DUAL --> DUMMY TABLE
;

SELECT *
  FROM DUAL
;
-- 2. 현재 시간을 "연-월-일" 포멧으로 조회한다.
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
  FROM DUAL
;
-- 3. 한 시간 전 시간을 "시:분:초" 포멧으로 조회한다.
SELECT TO_CHAR(SYSDATE, 'HH:MI:SS')
	 , TO_CHAR(SYSDATE, 'HH24:MI:SS') -- 자주 사용
  FROM DUAL
;

SELECT TO_CHAR(SYSDATE - 1 / 24, 'HH24:MI:SS')
  FROM DUAL
;
-- 4. EMPLOYEES 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
;
-- 5. DEPARTMENTS 테이블의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID 
	 , DEPARTMENT_NAME 
	 , MANAGER_ID 
	 , LOCATION_ID
  FROM DEPARTMENTS
;
-- 6. JOBS 테이블의 모든 정보를 조회한다.
SELECT JOB_ID 
 	 , JOB_TITLE 
 	 , MIN_SALARY 
 	 , MAX_SALARY 
  FROM JOBS
;
-- 7. LOCATIONS 테이블의 모든 정보를 조회한다.
SELECT LOCATION_ID 
	 , STREET_ADDRESS 
	 , POSTAL_CODE 
	 , CITY 
	 , STATE_PROVINCE 
	 , COUNTRY_ID 
  FROM LOCATIONS
;
-- 8. COUNTRIES 테이블의 모든 정보를 조회한다.
SELECT COUNTRY_ID 
	 , COUNTRY_NAME 
	 , REGION_ID 
  FROM COUNTRIES
;
-- 9. REGIONS 테이블의 모든 정보를 조회한다.
SELECT REGION_ID 
	 , REGION_NAME 
  FROM REGIONS
;
-- 10. JOB_HISTORY 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , START_DATE 
	 , END_DATE 
	 , JOB_ID 
	 , DEPARTMENT_ID 
  FROM JOB_HISTORY
;
-- 11. 상사사원번호를 중복없이 조회한다.
SELECT DISTINCT MANAGER_ID 
  FROM EMPLOYEES
;
-- 12. 90번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 90
;
-- 13. 90번, 100번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID IN (90, 100)
;
-- 14. 100번 상사의 직속 부하직원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE MANAGER_ID = 100
;
-- 15. 111번 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 111
;
-- 16. 직무 아이디가 AD_VP 인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE JOB_ID = 'AD_VP'
;
-- 17. 급여가 7000 이상인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE SALARY >= 7000
;
-- 18. 직무 아이디가 'PU_CLERK'인 사원 중 급여가 3000 이상인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE JOB_ID = 'PU_CLERK'
   AND SALARY >= 3000
;
-- 19. 급여가 2500, 3500, 7000 이 아니며 직업이 SA_REP 이나 ST_CLERK 인 사원들의 
--     모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID  
  FROM EMPLOYEES
 WHERE SALARY NOT IN (2500, 3500, 7000)
   AND JOB_ID IN ('SA_REP', 'ST_CLERK') 
;
-- 20. 커미션을 안받는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL 
;
-- 21. 커미션을 받는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL
;
-- 22. 이름의 첫 글자가 'D' 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'D%'
;
-- 23. 성의 마지막 글자가 'a' 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE LAST_NAME LIKE '%a'
;
-- 24. 전화번호에 '.124.'이 포함된 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '%.124.%'
;
-- 25. 이름이 4글자인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '____'
;
-- 26. 이름이나 성에 'A' 혹은 'a' 가 포함된 사원의 모든 정보를 조회한다.
--INLINE VIEW로 풀이 가능
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%A%'
    OR FIRST_NAME LIKE '%a%'
    OR LAST_NAME LIKE '%A%'
    OR LAST_NAME LIKE '%a%'
;


-- 27. 국가명이 6자리인 국가의 모든 정보를 조회한다.
SELECT COUNTRY_ID 
	 , COUNTRY_NAME 
	 , REGION_ID 
  FROM COUNTRIES
 WHERE COUNTRY_NAME LIKE '______'
;
-- 28. '20230222' 문자 데이터를 날짜로 변환해 조회한다.(DUAL)
SELECT '20230222'
	 , TO_DATE('20230222', 'YYYY-MM-DD')
	 , TO_DATE('20230222') -- 실제 운영하는 DB서버는 엄격함(사용X)
  FROM DUAL
;
-- 29. '20230222' 문자 데이터를 'YYYY-MM' 으로 변환해 조회한다.(DUAL)
SELECT TO_CHAR(TO_DATE('20230222', 'YYYY-MM-DD'), 'YYYY-MM')
  FROM DUAL
;
-- 30. '20230222130140' 문자 데이터를 'YYYY-MM-DD HH24:MI:SS' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(TO_DATE('20230222130140', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS')
  FROM DUAL
;
-- 31. '20230222' 날짜의 열흘 후의 날짜를 'YYYY-MM-DD' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(TO_DATE('20230222', 'YYYY-MM-DD') + 10, 'YYYY-MM-DD')
  FROM DUAL
;
-- 32. 직원의 입사일자를 '연-월-일' 형태로 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY-MM-DD')
  FROM EMPLOYEES 
;
-- 33. 2005년 09월에 입사한 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE HIRE_DATE >= TO_DATE('2005-09-01', 'YYYY-MM-DD')
   AND HIRE_DATE <= TO_DATE('2005-10-01', 'YYYY-MM-DD') -1
;

SELECT TO_DATE('20050901', 'YYYYMMDD')
  FROM DUAL
;

-- 34. 현재 시간으로부터 20년 전 보다 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE HIRE_DATE < ADD_MONTHS(SYSDATE, -20 * 12)
;
-- 35. 사원들의 정보 중 입사연도, 이름, 성만 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY')
	 , FIRST_NAME 
	 , LAST_NAME 
  FROM EMPLOYEES
;
-- 36. 사원들의 정보 중 입사연도, 입사월, 이름, 성만 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY')
	 , TO_CHAR(HIRE_DATE, 'MM')
	 , FIRST_NAME 
	 , LAST_NAME 
  FROM EMPLOYEES
;
-- 37. MOD 함수를 통해 사원번호가 홀수면 남자, 짝수면 여자 로 구분해 조회한다. MOD(값, 나눌값)
-- 38. 사원 모든 정보 중 이메일만 모두 소문자로 변경하여 조회한다.
-- 39. 사원의 급여를 TRUNC(소수점 버림) 함수를 사용해 100 단위는 버린채 다음과 같이 조회한다. 
--     예> 3700 -> 3000, 12700 -> 12000
-- 40. 100단위를 버린 사원의 급여 별 사원의 수를 조회한다.
-- 41. 모든 사원들의 이름을 10자리로 맞추어 조회한다.
-- 42. 사원의 이름과 성을 이용해 EMAIL과 같은 값으로 만들어 조회한다.
-- 43. 모든 사원들의 이름을 10자리로 변환해 조회한다. 예> 이름 => "        이름"
-- 44. 모든 사원들의 성을 10자리로 변환해 조회한다. 예> 성 => "성         "
-- 45. 모든 사원들의 모든 정보를 조회한다. 
--     단, 커미션을 받는 사원은 "커미션여부" 컬럼에 "Y"를, 아닌 경우 "N"으로 조회한다.
-- 46. 사원의 모든 정보를 조회한다. 
--     사원의 급여가 5000 이하이면 "사원", 
--                7000 이하이면 "대리", 
--                9000 이하이면 "과장", 
--                그 외에는 "임원" 으로 조회한다.

-- 47. 모든 사원들의 모든 정보를 급여 오름차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 ORDER BY SALARY ASC 
;
-- 48. 모든 사원들의 모든 정보를 이름 내림차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES 
 ORDER BY FIRST_NAME DESC 
;
-- 49. 모든 사원들의 모든 정보를 직무 오름차순, 급여 내림차순으로 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES 
 ORDER BY JOB_ID ASC 
 	 , SALARY DESC 
;
-- 50. 가장 늦게 입사한 사원의 모든 정보를 조회한다.

-- 51. 가장 일찍 입사한 사원의 모든 정보를 조회한다.

-- 52. 사내의 최고급여과 최저급여의 차이를 조회한다.
SELECT MAX(SALARY) - MIN(SALARY) -- 21,900
  FROM EMPLOYEES
;
-- 53. 102번 직원의 직속 부하직원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID) -- 1
  FROM EMPLOYEES
 WHERE MANAGER_ID = 102
;
-- 54. 113번 직원의 직속 부하직원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID) -- 0
  FROM EMPLOYEES
 WHERE MANAGER_ID = 113
;

-- 55. 'SA_REP' 직무인 직원 중 가장 높은 급여과 가장 낮은 급여를 조회한다.
SELECT MAX(SALARY) -- 11,500
	 , MIN(SALARY) -- 6,100
  FROM EMPLOYEES
 WHERE JOB_ID = 'SA_REP'
;
-- 56. 부서아이디별 평균 급여를 조회한다.
SELECT DEPARTMENT_ID 
	 , AVG(SALARY)
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID 
;
-- 57. 직무아이디별 평균 급여, 최고급여, 최저급여를 조회한다.
SELECT JOB_ID 
	 , AVG(SALARY)
	 , MAX(SALARY)
	 , MIN(SALARY)
  FROM EMPLOYEES
 GROUP BY JOB_ID 
;
-- 58. 직무아이디별 사원의 수를 조회한다.
SELECT JOB_ID 
	 , COUNT(EMPLOYEE_ID )
  FROM EMPLOYEES
 GROUP BY JOB_ID 
;
--59. 상사아이디별 부하직원의 수를 조회한다. 단, 부하직원이 2명 이하인 경우는 제외한다.
SELECT MANAGER_ID 
	 , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 GROUP BY MANAGER_ID 
HAVING COUNT(EMPLOYEE_ID) > 2
;
-- 60. 부서번호별 현재 시간으로부터 15년 전 보다 일찍 입사한 사원의 수를 조회한다.
SELECT DEPARTMENT_ID 
	 , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 WHERE HIRE_DATE < ADD_MONTHS(SYSDATE, 12 * -15)
 GROUP BY DEPARTMENT_ID 
;
-- 61. 커미션을 안받는 사원이 근무하는 도시를 조회한다.

-- 62. 회사 전체의 평균 급여보다 많이 받는 사원들 중 
--     이름에 'u' 가 포함된 사원과 동일한 부서에서 근무중인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES 
 WHERE SALARY > (SELECT AVG(SALARY)
 				   FROM EMPLOYEES)
   AND DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID -- 중복번호가 있음
 						   FROM EMPLOYEES 
 						  WHERE FIRST_NAME LIKE '%u%')
 ;
-- 63. 이름이 'Renske' 인 사원의 급여과 같은 급여를 받는 사원의 모든 정보를 조회한다. 
--     단, 'Renske' 사원은 조회에서 제외한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES 
 WHERE SALARY = (SELECT SALARY 
 				   FROM EMPLOYEES
 				  WHERE FIRST_NAME = 'Renske')
   AND FIRST_NAME != 'Renske'
;
-- 64. 평균 급여보다 많이 받는 사원들의 사원번호, 이름, 성, 급여를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , SALARY 
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
 				   FROM EMPLOYEES)
;
  
-- 65. 평균 급여보다 적게 받는 사원들의 사원번호, 급여, 부서번호를 조회한다.
SELECT EMPLOYEE_ID 
	 , SALARY 
	 ,DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE SALARY < (SELECT AVG(SALARY)
 				   FROM EMPLOYEES)
;
-- 66. 가장 많은 급여를 받는 사원의 사원번호, 이름, 급여를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , SALARY 
  FROM EMPLOYEES
 WHERE SALARY = (SELECT MAX(SALARY)
 				   FROM EMPLOYEES)
;
-- 67. 자신의 상사보다 더 많은 급여를 받는 사원의 모든 정보를 조회한다.
-- 68. 자신의 상사보다 더 일찍 입사한 사원의 모든 정보를 조회한다.
-- 69. 가장 많은 커미션을 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE COMMISSION_PCT = (SELECT MAX(COMMISSION_PCT )
 				   		   FROM EMPLOYEES)
;
-- 70. 가장 적은 커미션을 받는 사원의 급여과 커미션을 조회한다.
SELECT SALARY 
	 , COMMISSION_PCT 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT = (SELECT MIN(COMMISSION_PCT )
 				   		   FROM EMPLOYEES)
;
-- 71. 사원이 속한 부서의 평균급여보다 적게 받는 사원의 모든 정보를 조회한다.
-- 72. 50번 부서의 부서장의 이름, 성, 급여를 조회한다.
SELECT FIRST_NAME
	 , LAST_NAME 
	 , SALARY 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = (SELECT MANAGER_ID 
 					    FROM DEPARTMENTS
 					   WHERE DEPARTMENT_ID = 50)
;
-- 73. 사원이 없는 부서명을 조회한다.

--사원이 근무하는 부서의 번호
SELECT DISTINCT DEPARTMENT_ID --중복제거
  FROM EMPLOYEES
;

SELECT DEPARTMENT_NAME 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID NOT IN (SELECT DISTINCT DEPARTMENT_ID 
 						       FROM EMPLOYEES
 						       WHERE DEPARTMENT_ID IS NOT NULL) --NULL은 NOT IN으로 비교할수없음(!=연산불가)
;
-- 74. 직무가 변경된 사원의 모든 정보를 조회한다.
--사원번호가 JOBHISTORY에 존재
SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (SELECT DISTINCT EMPLOYEE_ID 
 				         FROM JOB_HISTORY)
;
-- 75. 직무가 변경된적 없는 사원의 모든 정보를 조회한다.
-- 사원번호가
SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN (SELECT DISTINCT EMPLOYEE_ID 
 				             FROM JOB_HISTORY)
;
-- 76. 직무가 가장 많이 변경된 부서의 이름을 조회한다.
-- 77. 근무중인 사원이 없는 도시를 조회한다.

-- 78. 급여가 7000 에서 12000 사이인 사원이 근무중인 도시를 조회한다.

-- 79. 'Seattle' 에서 근무중인 사원의 직무명을 중복없이 조회한다.

-- 80. 부서가 없는 국가명을 조회한다.

-- 81. 'Europe' 에서 근무중인 사원들의 모든 정보를 조회한다.

-- 82. 'Seattle' 에서 근무중인 사원의 이름, 성, 급여, 부서명 을 조회한다.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE D.LOCATION_ID = (SELECT LOCATION_ID
 						  FROM LOCATIONS
 						 WHERE CITY = 'Seattle')
;
-- 83. 'Seattle' 에서 근무하지 않는 모든 사원의 이름, 성, 급여, 부서명, 도시를 조회한다.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY 
	 , D.DEPARTMENT_NAME 
	 , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.CITY != 'Seattle'
;
-- 84. 모든 사원들의 이름, 성, 급여, 부서명을 부서번호로 내림차순 정렬하여 조회한다.

-- 85. 2007년에 직무가 변경된 사원들의 현재 직무명, 부서명, 사원번호, 이름, 성을 조회한다.
SELECT J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 WHERE E.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID 
 						   FROM JOB_HISTORY
 						  WHERE START_DATE >= TO_DATE('2007-01-01', 'YYYY-MM-DD')
 						    AND START_DATE < TO_DATE('2008-01-01', 'YYYY-MM-DD'))
;
 
-- 86. 부서장이 없는 부서명 중 첫 글자가 'C' 로 시작하는 부서명을 조회한다.
SELECT DEPARTMENT_NAME 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
 						   FROM DEPARTMENTS
 						  WHERE MANAGER_ID IS NULL)
   AND DEPARTMENT_NAME LIKE ('C%') 
;

SELECT DEPARTMENT_NAME 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
 						   FROM DEPARTMENTS
 						  WHERE MANAGER_ID IS NULL) 
;
-- 87. 지역변호가 1000 ~ 1999 사이인 지역내 부서의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID 
	 , DEPARTMENT_NAME
	 , MANAGER_ID 
	 , LOCATION_ID 
  FROM DEPARTMENTS
  WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID 
  						  FROM LOCATIONS 
  						 WHERE LOCATION_ID > 1000
  						   AND LOCATION_ID < 1999)
  
;
-- 88. 국가 아이디가 'C'로 시작하는 국가의 지역을 모두 조회한다.
SELECT LOCATION_ID 
	 , STREET_ADDRESS 
	 , POSTAL_CODE 
	 , CITY 
	 , STATE_PROVINCE 
	 , COUNTRY_ID 
  FROM LOCATIONS 
 WHERE COUNTRY_ID IN (SELECT DISTINCT COUNTRY_ID 
 						FROM COUNTRIES
 					   WHERE COUNTRY_ID LIKE 'C%')
;
-- 89. 109번 사원의 입사일 부터 1년 동안 입사한 사원의 모든 정보를 조회한다.
--2002-08-16

SELECT  EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE HIRE_DATE >= (SELECT HIRE_DATE 
 					   FROM EMPLOYEES
 					  WHERE EMPLOYEE_ID = 109)	
   AND HIRE_DATE <= (SELECT ADD_MONTHS(HIRE_DATE, 12) 
 					  FROM EMPLOYEES
					 WHERE EMPLOYEE_ID = 109)		
;
-- 90. 가장 먼저 입사한 사원의 입사일로부터 2년 동안 입사한사원의 모든 정보를 조회한다.
-- 가장 먼저 입사한 사원의 입사일
SELECT MIN(HIRE_DATE) --2001.01.13
  FROM EMPLOYEES
;
-- 2001.01.13부터 2년
SELECT ADD_MONTHS(MIN(HIRE_DATE), 24)
  FROM EMPLOYEES
;

SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE HIRE_DATE >= (SELECT MIN(HIRE_DATE)
 					   FROM EMPLOYEES)
   AND HIRE_DATE <= (SELECT ADD_MONTHS(MIN(HIRE_DATE), 24)
   					   FROM EMPLOYEES)
;
-- 91. 가장 늦게 입사한 사원의 입사일의 1년 전보다 일찍 입사한 사원의 모든 정보를 조회한다.
--가장 늦게 입사한 사원의 입사일
SELECT EMPLOYEE_ID
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE HIRE_DATE < (SELECT ADD_MONTHS(MAX(HIRE_DATE), -12)
 					  FROM EMPLOYEES)
;
-- 92. 사원들이 근무하는 부서명, 이름, 성을 조회한다.
SELECT D.DEPARTMENT_NAME 
 	 , E.FIRST_NAME 
 	 , E.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
-- 93. 우편번호가 5자리인 도시에서 근무하는 사원명, 부서명, 도시명, 우편번호를 조회한다.
--

SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
	 , L.CITY 
	 , L.POSTAL_CODE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.CITY IN (SELECT DISTINCT CITY
 					FROM LOCATIONS
 				   WHERE POSTAL_CODE LIKE '_____')
;
-- 94. 부서장이 있는 부서명 중 첫 글자가 'S' 로 시작하는 부서에서 근무중인 사원의 
--     이름과 직무명, 부서명을 조회한다.
SELECT E.FIRST_NAME 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE D.MANAGER_ID IS NOT NULL 
   AND D.DEPARTMENT_NAME LIKE 'S%'
    
;
-- 95. 90, 60, 100번 부서에서 근무중인 사원의 이름, 성, 부서명을 조회한다.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE D.DEPARTMENT_ID IN (95, 90, 60, 100)
;
-- 96. 부서명이 5글자 미만인 부서에서 근무중인 사원의 이름, 부서명을 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE D.DEPARTMENT_NAME NOT LIKE '_____%' --LENGTH()
;								
-- 97. 도시명에 띄어쓰기 " " 가 포함된 도시에서 근무중인 사원들의 부서명, 도시명, 사원명을 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , L.CITY 
	 , E.FIRST_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.CITY LIKE '% %'
;
  
  
-- 98. 우편번호에 공백이 없는 도시에서 근무하는 사원의 이름, 부서명, 우편번호를 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
	 , L.POSTAL_CODE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.POSTAL_CODE NOT LIKE '% %'
;
-- 99. "주"가 없는 도시에서 근무하는 사원의 이름, 도시를 조회한다.
SELECT E.FIRST_NAME 
	 , L.CITY  
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.STATE_PROVINCE IS NULL
;
  
-- 100. 사원들의 사원번호, 이름, 성, 상사의 사원번호, 상사의 이름, 상사의 성을 조회한다.
SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E2.EMPLOYEE_ID 
	 , E2.FIRST_NAME 
	 , E2.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES E2
 	ON E.MANAGER_ID = E2.EMPLOYEE_ID 
;
-- 101. 직무가 변경된 사원의 과거 직무명과 현재 직무명을 조회한다.
SELECT PAST_J.JOB_TITLE 
	 , J.JOB_TITLE  
  FROM EMPLOYEES E 
 INNER JOIN JOBS J -- 현재 직무
    ON E.JOB_ID = J.JOB_ID 
 INNER JOIN JOB_HISTORY JH -- 과거 직무
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
 INNER JOIN JOBS PAST_J
    ON JH.JOB_ID = PAST_J.JOB_ID 
;
-- 102. 가장 적은 급여를 받는 사원의 부서명, 이름, 성, 급여, 부서장사원번호를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , E.FIRST_NAME 
	 , E.SALARY 
	 , D.MANAGER_ID 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE E.SALARY = (SELECT MIN(SALARY)
 					 FROM EMPLOYEES)
;
    
-- 103. 부서명별 사원의 수를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , COUNT(E.EMPLOYEE_ID )
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
;
-- 104. 대륙명별 사원의 수를 조회한다.
SELECT R.REGION_NAME 
	 , COUNT(E.EMPLOYEE_ID )
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON C.REGION_ID = R.REGION_ID
 GROUP BY R.REGION_NAME 
;
-- 105. 직무명별 최소급여를 조회한다.
SELECT J.JOB_TITLE 
	 , MIN(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 GROUP BY J.JOB_TITLE 
;
-- 106. 부서명별 최대급여를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , MAX(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
;
-- 107. 직무명별 평균급여를 평균급여순으로 오름차순 정렬하여 조회한다.
SELECT J.JOB_TITLE 
	 , AVG(E.SALARY) AS SAL_AVG
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 GROUP BY J.JOB_TITLE 
 ORDER BY SAL_AVG ASC
;
-- 108. 부서명별 평균급여를 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , AVG(SALARY) AS SAL_AVG
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
 ORDER BY SAL_AVG DESC
;
-- 109. 부서명별 급여의 합을 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , SUM(SALARY) AS SAL_SUM
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
 ORDER BY SAL_SUM DESC
;
-- 110. 직무명별 사원의 수를 오름차순 정렬하여 조회한다.
SELECT J.JOB_TITLE 
	 , COUNT(E.EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
 GROUP BY J.JOB_TITLE 
 ORDER BY EMP_CNT ASC
;
-- 111. 직무명, 부서명 별 사원 수, 평균급여를 조회한다.?
-- 부서명별 사원수와 평균급여
SELECT J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , COUNT(E.EMPLOYEE_ID)
	 , AVG(E.SALARY)
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON E.JOB_ID  = J.JOB_ID 
 GROUP BY J.JOB_TITLE 
 	 , D.DEPARTMENT_NAME
;



-- 112. 도시별 사원 수를 조회한다.
SELECT L.CITY
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 GROUP BY L.CITY 
;
-- 113. 국가별 사원 수, 최대급여, 최소급여를 조회한다.
SELECT C.COUNTRY_ID 
	 , COUNT(E.EMPLOYEE_ID)
	 , MAX(E.SALARY)
	 , MIN(E.SALARY)
  FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID 
 GROUP BY C.COUNTRY_ID 
;

-- 114. 국가별로 급여가 5000 이상인 사원의 수를 조회한다.
SELECT C.COUNTRY_ID 
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID 
 GROUP BY C.COUNTRY_ID 
HAVING SUM(E.SALARY) >= 5000
;

-- 115. 부서명, 직무명 별 평균 급여를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
	 , AVG(E.SALARY )
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN JOBS J
    ON E.JOB_ID =J.JOB_ID 
 GROUP BY D.DEPARTMENT_NAME 
 	 , J.JOB_TITLE 
;
-- 116. 도시명, 직무명 별 사원의 수를 조회한다.
SELECT L.CITY  
	 , J.JOB_TITLE 
	 , COUNT(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN JOBS J
    ON E.JOB_ID =J.JOB_ID 
 GROUP BY L.CITY 
 	 , J.JOB_TITLE 
;

-- 117. 부서명, 직무명 별 평균 급여 중 가장 작은 평균급여를 받는 부서명, 직무명을 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN JOBS J
    ON E.JOB_ID =J.JOB_ID 
 GROUP BY D.DEPARTMENT_NAME 
     , J.JOB_TITLE
 HAVING AVG(E.SALARY) = (SELECT MIN(AVG(E.SALARY)) --2780
 						   FROM EMPLOYEES E
			   			  INNER JOIN DEPARTMENTS D
  				 			 ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
					      INNER JOIN JOBS J
    					     ON E.JOB_ID =J.JOB_ID 
					      GROUP BY D.DEPARTMENT_NAME 
 				  			  , J.JOB_TITLE)
;
-- 118. 대륙명별 사원 수를 대륙명으로 오름차순 정렬하여 조회한다.
SELECT R.REGION_NAME
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON C.REGION_ID = R.REGION_ID
 GROUP BY R.REGION_NAME 
 ORDER BY COUNT(E.EMPLOYEE_ID) ASC
; 

-- 119. 직무명별 최대급여보다 더 많은 급여를 받는 사원의 모든 정보를 조회한다.
-- 120. 입사연도별 최소급여를 조회한다.
-- 121. 사원 이름의 글자수 별 사원의 수를 조회한다.
-- 122. 사원 성의 글자수 별 사원의 수를 조회한다.
-- 123. 커미션을 포함한 급여가 10000 이상인 사원의 모든 정보를 조회한다.
-- 124. 국가 아이디의 첫 글자와 국가명의 첫 글자가 다른 모든 국가를 조회한다.
-- 125. 이름의 첫 번째 글자별 평균급여를 조회한다.
-- 126. 많은 급여를 받는 10명을 조회한다.
-- 127. 많은 급여를 받는 사원 중 11번 째 부터 20번째를 조회한다.
-- 128. 가장 적은 급여를 받는 중 90번 째 부터 100번째를 조회한다.
-- 129. 가장 적은 급여를 받는 사원의 상사명, 부서명을 조회한다.
SELECT E_MAN.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN EMPLOYEES E_MAN
    ON E.MANAGER_ID = E_MAN.EMPLOYEE_ID 
 WHERE E.SALARY = (SELECT MIN(SALARY)
 					 FROM EMPLOYEES)
;
-- 130. 'PU_CLERK' 직무인 2번째 부터 5번째 사원의 부서명, 직무명을 조회한다.
-- 131. 월별 최대급여 중 2번째 부터 4번째 데이터만 조회한다.
-- 132. 근무중인 사원이 가장 많은 도시와 사원의 수를 조회한다.  
-- 133. 사원의 수가 가장 많은 부서명, 사원의 수를 조회한다.
-- 134. 가장 많은 부서가 있는 도시를 조회한다.
-- 135. 가장 많은 사원이 있는 부서의 국가명을 조회한다.
-- 136. 'Europe' 에서 가장 많은 사원들이 있는 부서명을 조회한다.
-- 137. 100번 사원의 모든 부하직원을 계층조회한다. 단, LEVEL이 4인 사원은 제외한다.
 SELECT EMPLOYEE_ID
 	  , FIRST_NAME 
 	  , LAST_NAME 
 	  , MANAGER_ID 
   FROM EMPLOYEES
  WHERE LEVEL!= 4
  START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID 
;
-- 138. 101번 사원의 모든 부하직원 들의 이름, 성, 상사사원번호 계층 조회한다.
 SELECT EMPLOYEE_ID
 	  , FIRST_NAME 
 	  , LAST_NAME 
 	  , MANAGER_ID 
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID = 101
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID 
;
-- 139. 114번 직원의 모든 상사들의 이름, 성, 상사사원번호 계층 조회한다.
SELECT EMPLOYEE_ID
 	  , FIRST_NAME 
 	  , LAST_NAME 
 	  , MANAGER_ID 
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID = 114
CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID 
;
-- 140. 114번 직원의 모든 상사들의 이름, 성, 상사사원번호 역순으로 계층 조회한다.
 SELECT LEVEL
 	  , EMPLOYEE_ID
 	  , FIRST_NAME 
 	  , LAST_NAME 
 	  , MANAGER_ID 
   FROM EMPLOYEES
  START WITH EMPLOYEE_ID = 114
CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID 
  ORDER BY LEVEL DESC
;
-- 141. 부서별 사원의 수를 조인을 이용해 다음과 같이 조회한다."부서명 (사원의 수)"
-- 142. 부서별 사원의 수를 스칼라쿼리를 이용해 다음과 같이 조회한다. "부서명 (사원의 수)"
-- 143. 사원의 정보를 다음과 같이 조회한다. "사원번호 번 사원의 이름은 성이름 입니다."
-- 144. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. 
--      "사원번호 번 사원의 상사명은 상사명 입니다."
-- 145. 사원의 정보를 조인을 이용해 다음고 같이 조회한다. "사원명 (직무명)"
-- 146. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. "사원명 (직무명)"
-- 147. 부서별 급여 차이(최고급여 - 최저급여)가 가장 큰 부서명을 조회한다.
-- 148. 부서별 급여 차이(최고급여 - 최저급여)가 가장 큰 부서에서 근무하는 사원들의 직무명을 
--      중복없이 조회한다.
-- 149. 부하직원이 없는 사원의 모든 정보를 조회한다.
-- 내가 상사면 부하직원의 매니저아이디에 없어야한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , EMAIL 
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES E
 WHERE E.EMPLOYEE_ID NOT IN (SELECT DISTINCT MANAGER_ID 
 							   FROM EMPLOYEES 
 							  WHERE E.MANAGER_ID IS NOT NULL)
;
-- 150. 사원번호가 100번인 사원의 사원번호, 이름과 
--      사원번호로 내림차순 정렬된 사원의 사원번호, 이름을 조회한다.
/*조회 예
--------------------
100    Steven
206    William
205    Shelley
204    Hermann
203    Susan
202    Pat
201    Michael
200    Jennifer
199    Douglas
198    Donald
197    Kevin
196    Alana
...
*/
