/*해당 문제의 건수와 결과를 캡처해 댓글로 작성하세요.*/

 

--1. 사원 이름과 부서명을 함께 조회하시오.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;

--2. 사원 이름과 직무명을 함께 조회하시오.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
;
--3. 사원 이름, 부서명, 근무 도시를 조회하시오.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , D.DEPARTMENT_NAME 
	 , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
;
--4. 부서명과 국가명을 조회하시오.
SELECT D.DEPARTMENT_NAME 
	 , C.COUNTRY_NAME 
  FROM DEPARTMENTS D
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID 
;
 
--5. 직무변경 이력이 있는 사원의 이름과 이전 직무를 조회하시오.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , JH.JOB_ID 
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH
    ON E.EMPLOYEE_ID  = JH.EMPLOYEE_ID 
;
--6. 부서번호와 부서장의 이름을 조회하시오.
SELECT DISTINCT E.DEPARTMENT_ID 
	 , E_MAN.FIRST_NAME 
	 , E_MAN.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN EMPLOYEES E_MAN
    ON D.MANAGER_ID = E_MAN.EMPLOYEE_ID 
;
--7. 사원 이름, 부서명, 직무명을 한 번에 조회하시오.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
    ON E.JOB_ID  = J.JOB_ID 
;
--8. 각 사원의 이름과 그 사원의 상사 이름을 함께 조회하시오.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E_MAN.FIRST_NAME 
	 , E_MAN.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES E_MAN
    ON E.MANAGER_ID = E_MAN.EMPLOYEE_ID 
;
--9. 모든 사원의 이름, 급여, 직무명, 부서명, 도시명, 주소, 우편번호, 국가명, 대륙명을 조회하시오.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , L.CITY 
	 , L.STREET_ADDRESS 
	 , L.POSTAL_CODE 
	 , C.COUNTRY_NAME 
	 , R.REGION_NAME 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON C.REGION_ID = R.REGION_ID 
  
;
--10. 직무변경 이력이 있는 사원의 이름, 이전 직무명, 이전 부서명을 조회하시오.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH
    ON E.EMPLOYEE_ID  = JH.EMPLOYEE_ID 
 INNER JOIN JOBS J
    ON JH.JOB_ID = J.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
--11. 직무변경 이력이 있는 사원의 이름, 현재 직무명, 현재 부서명을 조회하시오.
SELECT E.FIRST_NAME
	 , E.LAST_NAME 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
--12. 직무변경 이력이 있는 사원의 이름, 이전에 근무했던 부서의 번호, 이전에 근무했던 도시의 이름을 조회하시오.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , D_PAST.DEPARTMENT_ID 
	 , L_PAST.CITY 
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
 INNER JOIN DEPARTMENTS D_PAST
    ON JH.DEPARTMENT_ID = D_PAST.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L_PAST
    ON D_PAST.LOCATION_ID = L_PAST.LOCATION_ID 
 
;
--13. 'Tokyo'시에서 근무중인 사원의 이름을 조회하시오.
SELECT FIRST_NAME 
	 , LAST_NAME 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = (SELECT E.EMPLOYEE_ID 
 					    FROM EMPLOYEES E
 					   INNER JOIN DEPARTMENTS D
    					  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
    				   INNER JOIN LOCATIONS L
    				      ON D.LOCATION_ID = L.LOCATION_ID 
    				     AND L.CITY = 'Tokyo')
;

--14. 'Kuwait'국가에서 근무중인 사원의 직무명을 중복없이 조회하시오.
SELECT DISTINCT J.JOB_TITLE  
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 WHERE E.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID
                           FROM EMPLOYEES E2
                           INNER JOIN DEPARTMENTS D
    						  ON E2.DEPARTMENT_ID = D.DEPARTMENT_ID 
 						   INNER JOIN LOCATIONS L
    						  ON D.LOCATION_ID = L.LOCATION_ID 
 						   INNER JOIN COUNTRIES C
      						  ON L.COUNTRY_ID = C.COUNTRY_ID 
  							 AND C.COUNTRY_NAME = 'Kuwait')
;