/*각 문제의 건수를 결과 캡처와 함께 댓글로 첨부하세요.*/

  

-- 1. 대륙, 국가, 도시, 부서, 직무별 사원의 수, 사원들의 평균 급여를 조회하세요.
SELECT R.REGION_ID 
 	 , C.COUNTRY_ID 
 	 , L.CITY 
 	 , D.DEPARTMENT_ID 
 	 , E.JOB_ID 
 	 , AVG(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON C.REGION_ID = R.REGION_ID 
 GROUP BY R.REGION_ID 
 	 , C.COUNTRY_ID 
 	 , L.CITY 
 	 , D.DEPARTMENT_ID 
 	 , E.JOB_ID 
;
-- 2. 각 부서장 사원번호별 사원의 수를 조회하고 사원의 수로 오름차순 정렬하세요.
SELECT D.MANAGER_ID 
	 , COUNT(E.EMPLOYEE_ID )
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 GROUP BY D.MANAGER_ID 
 ORDER BY COUNT(E.EMPLOYEE_ID ) ASC
;
-- 3. 직무가 받을 수 있는 평균 급여(MAX_SALARY, MIN_SALARY)보다 많은 급여를 받는 사원들을 직무별 사원의 수로 조회하세요.
SELECT E.JOB_ID
	 , COUNT(E.EMPLOYEE_ID )
  FROM EMPLOYEES E
 GROUP BY E.JOB_ID 
 HAVING E.SALARY > (SELECT AVG(SALARY)
 					 FROM EMPLOYEES
 					 GROUP BY JOB_ID)
;

SELECT E.SALARY
  FROM EMPLOYEES E
 GROUP BY E.JOB_ID 
 HAVING E.SALARY > (SELECT AVG(SALARY)
 					 FROM EMPLOYEES
 					 GROUP BY JOB_ID)
;

-- 이 직무를 가진 사원중에 급여가 더 높은 사원
-- 직무별 평균급여
SELECT JOB_ID
	 , AVG(SALARY)
  FROM EMPLOYEES
  GROUP BY JOB_ID
;
-- 4. 모든 부서장들의 부하직원들을 계층 조회하세요.
SELECT 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 START WITH D.MANAGER_ID IS NOT NULL
CONNECT BY PRIOR  
  ;